# Configurações do Spring
spring:
  # Configuração do JPA para desenvolvimento
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  # Configuração de datasource
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fastfood}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  # Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: local,test,prod
  # Upload de arquivos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  # Swagger/OpenAPI
  springdoc:
    api-docs:
      enabled: true
  # Spring Modulith
  autoconfigure:
    exclude:
      - org.springframework.modulith.events.jdbc.JdbcEventPublicationAutoConfiguration
  # Redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000
  # Cache
  cache:
    type: simple

# Logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.soat.fiap.food.core.api: DEBUG
    com.soat.fiap.food.core.api.product: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    org.springdoc: DEBUG

# CDN
app:
  cdn:
    base-url: ${APP_CDN_BASE_URL:http://localhost:8082}
    storage-directory: ${APP_CDN_STORAGE_DIRECTORY:${user.home}/cdn-storage}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
