spring:
  application:
    name: food-core-api

  # Perfil padrão (development)
  profiles:
    active: local

  # Configurações de banco de dados
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fastfood}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  # Spring Modulith
  autoconfigure:
    exclude:
      - org.springframework.modulith.events.jdbc.JdbcEventPublicationAutoConfiguration

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          jdbc:
            time_zone: UTC
      show-sql: false

  # Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: prod # Contexto padrão é prod (será sobrescrito em local)

  # SpringDoc
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha
      disable-swagger-default-url: true
      doc-expansion: none
      show-actuator: true

  # Upload de arquivos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

# Configurações de logging
logging:
  level:
    root: INFO
    com.soat.fiap.food.core.api: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springdoc: DEBUG

server:
  address: ${SERVER_ADDRESS:0.0.0.0} #endereço para testes
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /api
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always


# JWT Configuration
jwt:
  secret_key: ${JWT_SECRET:UOskZ5mykjrhRU8aHuT0sKaOj8Q9i+l6nFZzdpICF0zTSHi8PnbTQtUnKI6mUlNMrSdfQUpN59oWddOc4S3DXQ==}
  expiration: 3600

# Mercado Pago Configuration
mercado-pago:
  base-url: ${MERCADO_PAGO_BASE_URL:https://api.mercadopago.com/}
  token: ${MERCADO_PAGO_TOKEN:APP_USR-6067894635102235-051018-411ad7e519a24f5652d328ba205a2b9a-2430659417}
  user-id: ${MERCADO_PAGO_USER_ID:2430659417}
  pos-id: ${MERCADO_PAGO_POS_ID:POCMP001POS001}
  notification-url: ${MERCADO_PAGO_NOTIFICATION_URL:https://sua-url.ngrok-free.app/api/payments/webhook} # NGROK (Será sobrescrito em prod)

# Azure Storage Configuration
azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=https;AccountName=fastfoodcoreapi;AccountKey=zdptHpyapo/jatHe2DdaajF1zUv7UzC6T81NAWtKCHoEL4NJNOEqiJ7iFxyjutnaAwlUL5i7Ri4P+ASt9KfI4g==;EndpointSuffix=core.windows.net}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:images}
