spring:
  application:
    name: food-core-api
  # Perfil padrão (development)
  profiles:
    active: local
  # Configurações de banco de dados
  datasource:
    url: jdbc:postgresql://localhost:5432/fastfood
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false
  # Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: prod  # Contexto padrão é prod (será sobrescrito em local)
  # SpringDoc
  springdoc:
      swagger-ui:
          path: /swagger-ui.html
          operations-sorter: alpha
          tags-sorter: alpha
          disable-swagger-default-url: true
          doc-expansion: none
      show-actuator: true
  data:
    # Configuração do Redis
    redis:
      host: localhost
      timeout: 2000
      port: 6379

# Configurações de logging
logging:
  level:
    root: INFO
    com.soat.fiap.food.core.api: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springdoc: DEBUG

server:
  port: 8085
  servlet:
    context-path: /api
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

app:
  cdn:
    base-url: http://localhost:8082
    storage-directory: ${user.home}/cdn-storage

#JWT Configuration
jwt:
  secret_key: "${JWT_SECRET:UOskZ5mykjrhRU8aHuT0sKaOj8Q9i+l6nFZzdpICF0zTSHi8PnbTQtUnKI6mUlNMrSdfQUpN59oWddOc4S3DXQ==}"
  expiration: 3600

#Mercado Pago Configuration
mercado-pago:
  base-url: https://api.mercadopago.com/
  token: APP_USR-6067894635102235-051018-411ad7e519a24f5652d328ba205a2b9a-2430659417
  user-id: 2430659417
  pos-id: POCMP001POS001