# Configurações do servidor
server:
  port: ${SERVER_PORT:8080}

# Configurações do Spring
spring:
  # Configuração do JPA para desenvolvimento
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  # Configuração de datasource (funciona com variáveis de ambiente e fallback para desenvolvimento local)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/fastfood}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  # Liquibase para migrações de banco de dados
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  # Configuração para upload de arquivos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  # Configurações do Swagger/OpenAPI
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      operations-sorter: method
    show-actuator: true
  # Configurações do Spring Modulith

  # Excluir configurações problemáticas para o Spring Modulith
  autoconfigure:
    exclude:
      - org.springframework.modulith.events.jdbc.JdbcEventPublicationAutoConfiguration
  # Redis para cache
  data:
    redis:
      timeout: 2000
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

# Configurações de log para desenvolvimento
logging:
  level:
    root: INFO
    com.soat.fiap.food.core.api: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.modulith: DEBUG

# Configuração de CDN
app:
  cdn:
    base-url: ${CDN_BASE_URL:https://dev-cdn.soat.com.br}

# Habilitar todos endpoints do actuator em dev
management:
  endpoints:
    web:
      exposure:
        include: "*" 