spring:
  # Configuração do JPA para produção
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Usar apenas o contexto de produção
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: prod

  # Limitar endpoints do actuator em produção
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
    endpoint:
      health:
        show-details: when_authorized
  data:
    # Redis para cache
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      timeout: 2000

# Configurações do servidor
server:
  tomcat:
    max-threads: 200
    min-spare-threads: 20
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 2048
  port: ${SERVER_PORT:8080}

# Configurações da aplicação
app:
  # Configurações do CDN para produção
  cdn:
    root-path: ${APP_CDN_ROOT_PATH:/app/cdn}
    public-url: ${APP_CDN_PUBLIC_URL}
    base-url: ${CDN_BASE_URL}

# Configurações de log para produção
logging:
  level:
    root: WARN
    com.fastfood: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

#JWT Configuration
jwt:
  secret_key: "${JWT_SECRET:UOskZ5mykjrhRU8aHuT0sKaOj8Q9i+l6nFZzdpICF0zTSHi8PnbTQtUnKI6mUlNMrSdfQUpN59oWddOc4S3DXQ==}"
  expiration: 3600

#Mercado Pago Configuration
mercado-pago:
  base-url: https://api.mercadopago.com/
  token: APP_USR-6067894635102235-051018-411ad7e519a24f5652d328ba205a2b9a-2430659417
  user-id: 2430659417
  pos-id: POCMP001POS001
  notification-url: https://teste.com # definir posteriormente