apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    app: {{ include "prometheus.name" . }}
  namespace: {{ .Values.namespace.monitor.name }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-nodes'
        scheme: https
        kubernetes_sd_configs:
          - role: node
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
        relabel_configs:
          - source_labels: [__address__]
            target_label: __metrics_path__
            replacement: /metrics/cadvisor
            
      - job_name: "foodcore-api-metrics"
        metrics_path: {{.Values.api.ingress.path}}/actuator/prometheus
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ["{{ .Values.namespace.api.name }}"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: {{ include "api.fullname" . }}-service
            action: keep