apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secrets
  namespace: {{ .Values.namespace.api.name }}
type: Opaque
data:
  SPRING_DATASOURCE_URL: {{ .Values.postgresql.auth.url | printf "%s" | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.auth.username | printf "%s" | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | printf "%s" | b64enc }}
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.api.azure.blob.connectionString | printf "%s" | b64enc }}
  AZURE_STORAGE_CONTAINER_NAME: {{ .Values.api.azure.blob.containerName | printf "%s" | b64enc }}
  JWT_SECRET: {{ .Values.api.auth.jwt.secret | printf "%s" | b64enc }}
  JWT_EXPIRATION_TIME: {{ .Values.api.auth.jwt.expirationTime | printf "%s" | b64enc }}
  MERCADO_PAGO_TOKEN: {{ .Values.api.mercadoPago.token | printf "%s" | b64enc }}
  MERCADO_PAGO_USER_ID: {{ .Values.api.mercadoPago.userId | printf "%s" | b64enc }}
  MERCADO_PAGO_POS_ID: {{ .Values.api.mercadoPago.posId | printf "%s" | b64enc }}