apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}-config
  labels:
    app: {{ include "fluentd.name" . }}
data:
  FLUENT_ELASTICSEARCH_HOST: {{ include "elasticsearch.fullname" . }}-service
  FLUENT_ELASTICSEARCH_PORT: {{ .Values.elasticsearch.ports.rest | quote }}
  FLUENT_ELASTICSEARCH_SCHEME: {{ .Values.fluentd.elasticsearch.scheme | quote }}
  FLUENTD_SYSTEMD_CONF: {{ .Values.fluentd.systemdConf | quote }}