apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}-service
  labels:
    app: {{ include "api.name" . }}
spec:
  selector:
    app: {{ include "api.name" . }}
  ports:
    - port: {{ .Values.api.ports.port }}
      name: {{ .Values.api.ports.name }}