apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adminer.fullname" . }}-config
data:
  adminerDefaultServer: {{ include "postgresql.fullname" . }}-service
  adminerDesign: {{ .Values.adminer.design }}