apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
data:
  postgresql.conf: |
    # PostgreSQL configuration
    shared_preload_libraries = 'pg_stat_statements'
    log_statement = 'all'
    log_min_duration_statement = 0
    max_connections = {{ .Values.postgresql.config.maxConnections | default "100" }}
    shared_buffers = {{ .Values.postgresql.config.sharedBuffers | default "128MB" }}