apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
data:
  PGDATA: "{{ .Values.postgresql.volumes.postgrevolume.mountPath }}{{ .Values.postgresql.volumes.postgrevolume.dataFolder }}"