apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgresql.fullname" . }}-pv
  labels:
    app: {{ include "postgresql.name" . }}
spec:
  capacity:
    storage: {{ .Values.postgresql.storageSize }}
  
  accessModes:
    - ReadWriteOnce
  
  persistentVolumeReclaimPolicy: Retain

  storageClassName: manual
  
  hostPath:
    path: {{ .Values.postgresql.hostPath | quote }}
