apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secrets
  namespace: {{ .Values.namespace.api.name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
