apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-service
  labels:
    app: {{ include "postgresql.name" . }}
  namespace: {{ .Values.namespace.api.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app: {{ include "postgresql.name" . }}